// ═══════════════════════════════════════════════════════
// MITRA Flutter App — Entry Point
// ═══════════════════════════════════════════════════════

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';

import 'constants/colors.dart';
import 'router.dart';
import 'services/api_service.dart';
import 'firebase_options.dart'; // generated by flutterfire configure

// ── Background FCM handler ─────────────────────────────
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  debugPrint('🔔 Background FCM: ${message.messageId}');
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Load .env
  await dotenv.load(fileName: '.env');

  // Init Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  // Init Dio API client
  ApiService.instance.init();

  // Force portrait orientation
  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

  // Dark status bar
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor:        Colors.transparent,
    statusBarIconBrightness: Brightness.light,
    systemNavigationBarColor: MitraColors.bgDeep,
  ));

  runApp(
    // ProviderScope = Riverpod root (equivalent to React's QueryClientProvider)
    const ProviderScope(child: MitraApp()),
  );
}

class MitraApp extends ConsumerWidget {
  const MitraApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);

    return MaterialApp.router(
      title:               'MITRA',
      debugShowCheckedModeBanner: false,
      theme:               mitraTheme(),
      routerConfig:        router,
      // Localisation support (i18n)
      supportedLocales: const [
        Locale('en'),
        Locale('hi'),
        Locale('ta'),
        Locale('te'),
        Locale('kn'),
        Locale('bn'),
        Locale('mr'),
        Locale('gu'),
      ],
    );
  }
}
