// ═══════════════════════════════════════════════════════
// MITRA Flutter App — Entry Point
// ═══════════════════════════════════════════════════════

import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

import 'theme/theme_provider.dart';
import 'constants/colors.dart';
import 'router.dart';
import 'services/api_service.dart';
import 'firebase_options.dart'; // generated by flutterfire configure

// ── Background FCM handler ─────────────────────────────
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  debugPrint('🔔 Background FCM: ${message.messageId}');
}

Future<void> main() async {
  // ✨ 1. Capture the binding so we can pass it to the splash screen
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();

  // ✨ 2. FREEZE THE NATIVE SPLASH SCREEN!
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);

  debugPrint("🚦 Loading .env...");
  try {
    await dotenv.load(fileName: '.env');
  } catch (e) {
    debugPrint("⚠️ .env issue: $e");
  }

  debugPrint("🔥 Initializing Firebase...");
  try {
    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform);
    }
    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  } catch (e) {
    debugPrint("⚠️ Firebase skipped: $e");
  }

  debugPrint("🌐 Initializing API...");
  try {
    ApiService.instance.init();
  } catch (e) {
    debugPrint("⚠️ API issue: $e");
  }
  // ✨ NEW: Tell the phone to load its hard drive before showing the UI
  debugPrint("💾 Loading local storage...");
  final prefs = await SharedPreferences.getInstance();

  debugPrint("✅ ALL SYSTEMS GO! Launching UI...");
  runApp(
    ProviderScope(
      // ✨ NEW: We inject the loaded preferences into the ProviderScope we built earlier!
      overrides: [
        sharedPreferencesProvider.overrideWithValue(prefs),
      ],
      child: const MitraApp(),
    ),
  );
}

class MitraApp extends ConsumerWidget {
  const MitraApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);

    // ✨ 1. Grab the living theme from Riverpod
    final activeTheme = ref.watch(themeProvider);

    return MaterialApp.router(
      title: 'MITRA',
      debugShowCheckedModeBanner: false,
      color: MitraColors.saffron,

      // ✨ 2. Feed the dynamic theme directly into the root engine!
      // (Change 'getThemeData' to whatever method you use to get your ThemeData)
      theme: ThemeHelper.getThemeData(activeTheme),

      // 🚨 3. We removed darkTheme and themeMode because your custom ThemeHelper
      // now natively handles all the coloring for every scenario!

      routerConfig: router,
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        // ── The 22 Official Languages of India ──
        Locale('as'), // Assamese
        Locale('bn'), // Bengali
        Locale('brx'), // Bodo
        Locale('doi'), // Dogri
        Locale('gu'), // Gujarati
        Locale('hi'), // Hindi
        Locale('kn'), // Kannada
        Locale('ks'), // Kashmiri
        Locale('kok'), // Konkani
        Locale('mai'), // Maithili
        Locale('ml'), // Malayalam
        Locale('mni'), // Manipuri (Meitei)
        Locale('mr'), // Marathi
        Locale('ne'), // Nepali
        Locale('or'), // Odia
        Locale('pa'), // Punjabi
        Locale('sa'), // Sanskrit
        Locale('sat'), // Santali
        Locale('sd'), // Sindhi
        Locale('ta'), // Tamil
        Locale('te'), // Telugu
        Locale('ur'), // Urdu

        // ── Standard English Fallback ──
        Locale('en'), // English
      ],
    );
  }
}
