// ═══════════════════════════════════════════════════════
// MITRA Flutter App — Entry Point
// ═══════════════════════════════════════════════════════

import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'stores/theme_store.dart';
import 'constants/colors.dart';
import 'router.dart';
import 'services/api_service.dart';
import 'firebase_options.dart'; // generated by flutterfire configure

// ── Background FCM handler ─────────────────────────────
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  debugPrint('🔔 Background FCM: ${message.messageId}');
}

Future<void> main() async {
  // ✨ 1. Capture the binding so we can pass it to the splash screen
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();

  // ✨ 2. FREEZE THE NATIVE SPLASH SCREEN!
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);

  debugPrint("🚦 Loading .env...");
  try {
    await dotenv.load(fileName: '.env');
  } catch (e) {
    debugPrint("⚠️ .env issue: $e");
  }

  debugPrint("🔥 Initializing Firebase...");
  try {
    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform);
    }
    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  } catch (e) {
    debugPrint("⚠️ Firebase skipped: $e");
  }

  debugPrint("🌐 Initializing API...");
  try {
    ApiService.instance.init();
  } catch (e) {
    debugPrint("⚠️ API issue: $e");
  }
  // ✨ NEW: Tell the phone to load its hard drive before showing the UI
  debugPrint("💾 Loading local storage...");
  final prefs = await SharedPreferences.getInstance();

  debugPrint("✅ ALL SYSTEMS GO! Launching UI...");
  runApp(
    ProviderScope(
      // ✨ NEW: We inject the loaded preferences into the ProviderScope we built earlier!
      overrides: [
        sharedPreferencesProvider.overrideWithValue(prefs),
      ],
      child: const MitraApp(),
    ),
  );
}

class MitraApp extends ConsumerWidget {
  const MitraApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);

    // ✨ NEW: Watch the theme provider we just created
    final currentThemeMode = ref.watch(themeProvider);

    return MaterialApp.router(
      title: 'MITRA',
      debugShowCheckedModeBanner: false,
      theme: mitraTheme(), // Your default/light theme
      darkTheme: ThemeData.dark(), // Your dark theme fallback
      themeMode: currentThemeMode,
      routerConfig: router,
      supportedLocales: const [
        Locale('en'),
        Locale('hi'),
        Locale('ta'),
        Locale('te'),
        Locale('kn'),
        Locale('bn'),
        Locale('mr'),
        Locale('gu'),
      ],
    );
  }
}
